namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 
  clusterSelector:
    matchLabels:
      env: test

- name: prod1
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 
  clusterSelector:
    matchLabels:
      env: prod1
